name: Changelog Generator

on:
  # Run this workflow on a regular schedule automatically:
  push:
  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    

    - name: Generate changelog
      uses: ./
      with:
        token: ${{ secrets.GH_TOKEN }}
        projects: github/7714
        days: 21
        exclude_labels: no changelog,epic,Stale
        highlight_labels: bug,performance,feature
        